### ISSUE TITLE
How to build it _

### ISSUE THREAD

**Issue by simpleperson123** [Loksie/KoiVM-Virtualization#6]
How to build it? There are 2 projects and im confused. And if i run build.cmd file i get about 200 errors :((

**Comment by Xen-Corp** [comment]
If you cant build it, i find it hard to see you using it properly. You need to compile it using Visual Studio, and you need to add some dependencies.

**Comment by simpleperson123** [comment]
Stil not working for me? Where I can find some release of it???

**Comment by DevanshT02** [comment]
``[ERROR] Unknown error occurred.
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at KoiVM.Confuser.Internal.InitializePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in C:\Users\No\Desktop\Literally everything\KoiVM-Virtualization-master\KoiVM.Confuser\Internal\InitializePhase.cs:line 83
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in C:\Users\No\Desktop\Literally everything\KoiVM-Virtualization-master\Confuser.Core\ProtectionPipeline.cs:line 150
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in C:\Users\No\Desktop\Literally everything\KoiVM-Virtualization-master\Confuser.Core\ConfuserEngine.cs:line 244
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in C:\Users\No\Desktop\Literally everything\KoiVM-Virtualization-master\Confuser.Core\ConfuserEngine.cs:line 189
Failed at 11:36 AM, 0:00 elapsed.``

What exactly is going wrong? I added Koi.Confuser.exe to the confuserex using the "plugin + add"
